language: node_js
node_js: node
deploy: 
 provider: heroku
 api_key:
  secure: Yib2QxyBqdcVoWf8GgymwTm5dKBCWTF1EFEZcZnbtK5EkkeuUmMzkJ72qv//QnVnQlpY0dlEz567WEKVG/5581SzROohucILnWAEReR8QY99xDzqC+ZhrGt1wf0whDGgdeKS7t0DVGq5zLxU2Z6cjdMwndi9TussNjQuOMDjdJkasilclCEAI7Ca0234fkOy6vO8CrVRDrAwktMfBq1qP5Mwi1s49AOiwPJ1ArqTFvFUyJQrBz6D7PIsLiRn+QkWlA2YGX8aR3AS2gQVM5Yllo7vo/6wafRxsgdONvo0Dr6MEYPvO3eJF7O2wkq1Q9prc2uCyB8SzfF57JwqMScN/8U2s5IJTbChwduUfknoDjg1P/pE4yLKAPxkMz6uGUsa5/Vf+09iR5oJwWtuJgdQ19cuZDa4rWoTuMjyssDb+woxteSQ23ONopD+cnGpoUuiqa77MyRuhPTYl2RHljSh07zY9mQ0NFw+WxTxK5KsznYAXraILd1ePTdIG/Oy0nqD/v6zPmtJwJaUo0ASvp51nPsSQ+8E0XVhN8eVPCYfjopOtUCj35raNnjPr4knXy+GgFKFF+YpbJtgOpITQTDFQAt5B+CVao87fOMWkKENNZC/V3YTx6f2CgMLNuRM9kjbtrBRj1nbEz5MTE8VdF4DdbLKJpwbQRhVEWMXp0LeCHo=
 app: obscure-refuge-96931
 on:
  repo: jrvscm/strength-tracker
